theme: minima
baseurl: /rc-plugin-fail2ban
title: rc-plugin-fail2ban
description: "A Fail2Ban plugin for RoundCube"
author: "Matt Rude"

markdown: kramdown
permalink: pretty
highlighter: rouge
date: YYYY-MM-DD HH:MM

collections:
  posts:
    permalink: /posts/:title
